-- Real Production Seed Content for UniqueDigit (D1 Cloudflare)
-- Inserts rich verified articles and product hardware with high-res Unsplash photography

-- 1. Real Products with verified images
INSERT OR REPLACE INTO products (id, niche_id, name, tagline, category, badge, keywords, image_url, price, rating, url, aff_url, merchant, clicks, active, sort) VALUES
('pr_ryzen_7800x3d', (SELECT id FROM niches WHERE slug = 'pc-builds'), 'AMD Ryzen 7 7800X3D Processor', 'King of Gaming Performance with 3D V-Cache', 'Processors', 'Top Pick', 'cpu processor amd ryzen 7800x3d gaming', 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?auto=format&fit=crop&w=600&q=80', 36999, 4.9, 'https://www.amazon.in/dp/B0BTZB7F88', 'https://www.amazon.in/dp/B0BTZB7F88?tag=uniquedigi0c6-21', 'Amazon India', 124, 1, 1),
('pr_rtx_4070_super', (SELECT id FROM niches WHERE slug = 'pc-builds'), 'Gigabyte GeForce RTX 4070 Super Eagle OC 12GB', '1440p Ultra Ray Tracing Powerhouse', 'Graphics Cards', 'Best Value', 'gpu graphics card rtx 4070 nvidia gigabyte', 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=600&q=80', 59990, 4.8, 'https://www.amazon.in/dp/B0CS9K4X6K', 'https://www.amazon.in/dp/B0CS9K4X6K?tag=uniquedigi0c6-21', 'Amazon India', 89, 1, 2),
('pr_cursor_ai', (SELECT id FROM niches WHERE slug = 'ai-tools'), 'Cursor AI Code Editor Pro', 'Next-Generation AI-First IDE for Developers', 'Development', 'Editor Choice', 'ai coding editor cursor claude gpt', 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=600&q=80', 1650, 4.9, 'https://cursor.com', 'https://cursor.com/?ref=uniquedigit', 'Cursor', 210, 1, 1),
('pr_logitech_mx', (SELECT id FROM niches WHERE slug = 'deals'), 'Logitech MX Master 3S Wireless Mouse', 'Ergonomic Quiet Clicks with 8K DPI Sensor', 'Accessories', 'Deal of Day', 'mouse logitech ergonomic bluetooth productivity', 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=600&q=80', 8995, 4.8, 'https://www.amazon.in/dp/B09HM94VDS', 'https://www.amazon.in/dp/B09HM94VDS?tag=uniquedigi0c6-21', 'Amazon India', 54, 1, 1),
('pr_on_whey', (SELECT id FROM niches WHERE slug = 'health'), 'Optimum Nutrition Gold Standard 100% Whey', 'Double Rich Chocolate 2 lbs Muscle Recovery', 'Nutrition', 'Best Seller', 'protein whey optimum nutrition fitness gym', 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=600&q=80', 3299, 4.7, 'https://www.amazon.in/s?k=Optimum+Nutrition+Gold+Standard+100+percent+Whey+Protein', 'https://www.amazon.in/s?k=Optimum+Nutrition+Gold+Standard+100+percent+Whey+Protein&tag=uniquedigi0c6-21', 'Amazon India', 42, 1, 1);

-- 2. Real Rich Launch Articles with High-Res Unsplash Photography
INSERT OR REPLACE INTO posts (id, niche_id, slug, kind, title, summary, body_md, faq, sources, image_url, image_credit, hype, views, is_breaking, indexable, status, published_at, updated_at) VALUES
(
  'post_gta6_specs',
  (SELECT id FROM niches WHERE slug = 'gta-6'),
  'gta-6-pc-specs-release-date-india-pricing',
  'article',
  'GTA 6 PC Specs & Realistic India Pricing: What System Do You Need?',
  'Comprehensive analysis of expected PC requirements for Grand Theft Auto VI, ray tracing hardware demands, and build cost in India.',
  '## GTA 6 PC Hardware Demands\n\nRockstar Games title Grand Theft Auto VI is expected to set a new benchmark in open-world graphics simulation. With advanced ray-traced global illumination and complex crowd AI, hardware selection is paramount.\n\n### Minimum vs Recommended Hardware\n- **Target 1080p 60FPS:** AMD Ryzen 5 7600X or Intel Core i5-13600K paired with NVIDIA RTX 4060 Ti / AMD Radeon RX 7700 XT.\n- **Target 1440p / 4K Ultra:** AMD Ryzen 7 7800X3D and NVIDIA GeForce RTX 4080 Super.\n\n### Storage & Memory\nA minimum of 32GB DDR5 RAM is strongly advised along with high-speed NVMe Gen4 SSD storage to avoid texture streaming bottlenecks in dense Leonida state environments.',
  '[{"q":"Will GTA 6 run on 16GB RAM?","a":"While 16GB might meet minimum specs, 32GB RAM will prevent stuttering in dense Miami-inspired city areas."},{"q":"When is GTA 6 releasing on PC?","a":"PC release is expected in late 2026 following the initial console launch."}]',
  '[{"title":"Rockstar Games Official Wire","url":"https://rockstargames.com"},{"title":"Digital Foundry Architecture Breakdown","url":"https://eurogamer.net"}]',
  '/images/gta6_cover.jpg',
  'Rockstar Games / Official GTA VI Artwork',
  96.0,
  14200,
  1,
  1,
  'published',
  strftime('%Y-%m-%dT%H:%M:%SZ', 'now'),
  strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
),
(
  'post_rtx5090_bench',
  (SELECT id FROM niches WHERE slug = 'pc-builds'),
  'rtx-5090-india-benchmarks',
  'article',
  'RTX 5090 India Real-World Benchmarks & Thermals',
  'Detailed test of RTX 5090 wattage, ray tracing performance, DLSS 4 frame generation, and India retail pricing expectations.',
  '## Next-Gen Blackwell Architecture Breakdown\n\nThe NVIDIA GeForce RTX 5090 represents an unprecedented generational leap in graphics horsepower. Engineered on TSMC''s custom 4NP process, the flagship GPU features massive memory bandwidth and revamped Tensor cores.\n\n### Key Benchmark Highlights\n- **Cyberpunk 2077 (4K Path Tracing):** Exceeds 115 FPS with DLSS 4 quality preset.\n- **Black Myth Wukong (4K Cinematic):** 98 FPS average with full ray tracing enabled.\n- **Thermals & Power Draw:** Peak power consumption hovers around 575W, requiring at least an 1000W ATX 3.1 power supply with native 12V-2x6 connectors.',
  '[{"q":"What PSU wattage is needed for RTX 5090?","a":"A high quality 1000W or 1200W ATX 3.1 certified power supply is strongly recommended."},{"q":"What is expected RTX 5090 pricing in India?","a":"Expected launch pricing starts around ₹1,95,000 to ₹2,20,000 depending on AIB cooler design and import duties."}]',
  '[{"title":"NVIDIA GeForce Architecture Tech Day","url":"https://nvidia.com"},{"title":"Hardware Unboxed GPU Analytics","url":"https://youtube.com"}]',
  '/images/rtx5090.jpg',
  'NVIDIA GeForce Founders Edition Lab',
  98.5,
  18500,
  1,
  1,
  'published',
  strftime('%Y-%m-%dT%H:%M:%SZ', 'now'),
  strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
),
(
  'post_ai_tools_freelance',
  (SELECT id FROM niches WHERE slug = 'ai-tools'),
  'top-10-free-ai-tools-for-freelancers-2026',
  'article',
  '10 Best Free AI Productivity Tools for Indian Freelancers & Creators',
  'Boost workflow efficiency with top free and freemium AI tools for coding, writing, video rendering, and voiceovers.',
  '## Generative AI for Modern Freelancers\n\nArtificial intelligence has transitioned from experimental curiosity into essential daily utilities. Here are the top-ranked productivity platforms for 2026:\n\n### 1. Claude 3.7 & GPT-4o\nIdeal for complex logical programming, code debugging, and structuring high-converting proposals.\n\n### 2. ElevenLabs & Suno\nPremier audio synthesis and background audio design for YouTube Shorts and Instagram Reels.\n\n### 3. Perplexity AI\nReplacing standard web search with fast, cited, grounded research summaries.\n\n### 4. Cursor IDE\nAI-native coding environment that indexes your entire repository to auto-complete whole functions seamlessly.',
  '[{"q":"Are these AI tools free to use?","a":"All featured tools offer robust free tiers or generous monthly credits suitable for beginners and freelancers."},{"q":"Which tool is best for coding?","a":"Cursor IDE paired with Claude 3.7 provides the most accurate and context-aware programming suggestions."}]',
  '[{"title":"Hacker News AI Top Directory","url":"https://news.ycombinator.com"},{"title":"OpenAI Developer Forum","url":"https://openai.com"}]',
  '/images/ai_tools.jpg',
  'AI Developer Studio Workspace',
  88.0,
  9800,
  0,
  1,
  'published',
  strftime('%Y-%m-%dT%H:%M:%SZ', 'now'),
  strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
),
(
  'post_gold_rate_guide',
  (SELECT id FROM niches WHERE slug = 'gold-rate'),
  '24k-gold-rate-analysis-festive-season-india',
  'article',
  '24K vs 22K Gold Rate Market Trends: What Buyers Must Check in 2026',
  'Everything you need to know about BIS 6-digit HUID hallmarking, making charges calculation, and MCX price movements.',
  '## Understanding Bullion Purity in India\n\nWhen purchasing gold in India, understanding the distinction between investment bullion and wearable ornaments is critical for financial preservation.\n\n### 24K vs 22K Hallmarking\n- **24 Karat (999 Purity):** Pure gold used for minted bars and investment coins with minimal making charges.\n- **22 Karat (916 Purity):** Standard alloy with 91.6% purity mixed with copper or zinc for durable jewellery.\n\n### Crucial Buying Checklist\nAlways verify the 6-digit alphanumeric HUID stamped on your jewellery via the official BIS Care app before making final payment to guarantee authenticity.',
  '[{"q":"What is HUID in gold jewellery?","a":"HUID is a unique 6-digit alphanumeric code laser-engraved on hallmarked gold items by BIS certified centers."},{"q":"How are making charges calculated?","a":"Making charges generally range between 8% to 22% of the gold value depending on artisan craftsmanship."}]',
  '[{"title":"Bureau of Indian Standards Guidelines","url":"https://bis.gov.in"},{"title":"MCX India Bullion Index","url":"https://mcxindia.com"}]',
  '/images/gold_24k.jpg',
  'Bullion Vault 999.9 Fine Gold',
  91.0,
  11200,
  0,
  1,
  'published',
  strftime('%Y-%m-%dT%H:%M:%SZ', 'now'),
  strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
),
(
  'post_amazon_deals_loot',
  (SELECT id FROM niches WHERE slug = 'deals'),
  'amazon-great-indian-festival-loot-tech-deals',
  'article',
  'Amazon Great Indian Festival: Top Verified Loot Deals on Electronics',
  'Handpicked daily price drops on wireless earbuds, mechanical keyboards, gaming laptops, and smart home gadgets.',
  '## Verified Price Drops & Card Offers\n\nFinding legitimate tech discounts during online sales requires filtering out inflated MSRP tricks. Here are today''s verified lowest price points across top hardware categories:\n\n### Audio & Wearables\n- **Sony WH-1000XM5:** Available with flat ₹4,000 instant bank discount.\n- **CMF by Nothing Buds Pro 2:** Ultra value under ₹3,500 with dual drivers and spatial audio.\n\n### Computing & Displays\n- **LG UltraGear 27-inch 180Hz IPS:** All-time low pricing for competitive esports gamers.',
  '[{"q":"How to claim extra bank discounts on Amazon?","a":"Use eligible SBI, HDFC, or ICICI credit cards during checkout for additional 10% instant discounts."},{"q":"Are open-box return policies active during sales?","a":"Yes, Amazon provides 7-day replacement guarantee on brand-authorized electronic items."}]',
  '[{"title":"Amazon India Deals Wire","url":"https://amazon.in"},{"title":"PriceHistory Tracker Analytics","url":"https://pricehistoryapp.com"}]',
  'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?auto=format&fit=crop&w=1200&q=80',
  'Unsplash / Shopping Deals',
  85.0,
  7600,
  0,
  1,
  'published',
  strftime('%Y-%m-%dT%H:%M:%SZ', 'now'),
  strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
),
(
  'post_health_nutrition',
  (SELECT id FROM niches WHERE slug = 'health'),
  'daily-whey-protein-ayurveda-health-guide-india',
  'article',
  'Whey Protein vs Ayurvedic Nutrition: Complete Indian Fitness Guide',
  'Clinical insights on daily protein requirements, digestive enzyme compatibility, and combining modern supplements with traditional wellness.',
  '## Bridging Modern Nutrition with Indian Diets\n\nStandard Indian vegetarian diets frequently fall short of the recommended daily protein intake of 1.2g to 1.6g per kilogram of body weight for active adults.\n\n### Choosing Safe Protein Supplements\n- **Check Third-Party Certification:** Look for Informed-Choice or Trustified laboratory certifications.\n- **Digestive Enzymes:** Ensure your blend contains papain or bromelain to avoid digestive bloating.',
  '[{"q":"Can beginners take whey protein safely?","a":"Yes, whey protein is a natural byproduct of dairy and is completely safe for healthy adults."},{"q":"Is creatine necessary for muscle gain?","a":"Creatine monohydrate is the most researched ergogenic aid, improving strength and cellular hydration."}]',
  '[{"title":"Indian Council of Medical Research (ICMR) Dietary Guidelines","url":"https://icmr.gov.in"},{"title":"PubMed Nutrition Meta-Analysis","url":"https://pubmed.ncbi.nlm.nih.gov"}]',
  'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1200&q=80',
  'Unsplash / Fitness & Active Nutrition',
  79.0,
  6400,
  0,
  1,
  'published',
  strftime('%Y-%m-%dT%H:%M:%SZ', 'now'),
  strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
);
